# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := nc_editor

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

nc_editor: 
	@echo "==== Building nc_editor ($(config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   nc_editor"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
